development:
  adapter: postgresql
  database: js_course_2013_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: js_course_2013_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: js_course_2013_prod
  pool: 5
  timeout: 5000
